version: '3.8'

services:
  python-kafka-tensorflow:
    image: python:3.8-slim
    command: tail -f /dev/null
    volumes:
      - whisper_text_model_builder:/data  
    tty: true  
    container_name: whisper-ollama-message-generator-container
    environment:
      - TZ=America/Detroit
      - RELEASE_VERSION=${RELEASE_VERSION}
      - SOURCE_TOPIC_NAME=${SOURCE_TOPIC_NAME}
      - DESTINATION_TOPIC_NAME=${DESTINATION_TOPIC_NAME}
      - GROUP_ID=${GROUP_ID}
      - BROKER=${BROKER}
      - QUERY=${QUERY}
      - MODEL_NAME=${MODEL_NAME}
      - OLLAMA_PATH=${OLLAMA_PATH}
    networks:
      - alpine-net
    entrypoint: |
      /bin/bash -c "
      apt-get update && apt-get install -y --no-install-recommends git curl python3-venv;
      python3 -m venv /venv;
      source /venv/bin/activate;
      pip install --no-cache-dir pytz kafka-python python-dotenv tensorflow schedule;

      if [ ! -d /data/whisper-ollama-message-generator-v${RELEASE_VERSION} ]; then
        mkdir -p /data/whisper-ollama-message-generator-v${RELEASE_VERSION} && \
        curl -L https://github.com/DevinMB/whisper-ollama-message-generator/archive/refs/tags/v${RELEASE_VERSION}.tar.gz | tar xz --strip-components=1 -C /data/whisper-ollama-message-generator-v${RELEASE_VERSION};
      fi
      
      python3 /data/whisper-ollama-message-generator-v${RELEASE_VERSION}/whisper-ollama-message-generator.py;
      "

networks:
  alpine-net:
    driver: bridge

volumes:
  whisper_text_model_builder:  
